// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUgeyWs8aRx9SC54IVAws0R58N7XsULOQ',
    appId: '1:1036670076322:web:7f46fdbf2edb8287069efb',
    messagingSenderId: '1036670076322',
    projectId: 'to-do-11a1c',
    authDomain: 'to-do-11a1c.firebaseapp.com',
    storageBucket: 'to-do-11a1c.appspot.com',
    measurementId: 'G-7BC7HJK94N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2lo0dmcfzw5Snh2re6TRDVG_G7ym6YpE',
    appId: '1:1036670076322:android:bdd5ee5c2714ae5c069efb',
    messagingSenderId: '1036670076322',
    projectId: 'to-do-11a1c',
    storageBucket: 'to-do-11a1c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4XwMXOj898d4rWptPzj05HMA0b8Hv4MQ',
    appId: '1:1036670076322:ios:f2d9d5e7acfee5b9069efb',
    messagingSenderId: '1036670076322',
    projectId: 'to-do-11a1c',
    storageBucket: 'to-do-11a1c.appspot.com',
    iosClientId: '1036670076322-jkc5f6o5cj7q7igrgfm8a9sca44oco3a.apps.googleusercontent.com',
    iosBundleId: 'com.darkwolf.todo',
  );
}
